general:
  curvedb: pyrpl
  loglevel: debug
test:
  max_communication_time: 0.5
  reads_per_na_cycle: 7.0
pyrpl:
  background_color: ''
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: remote_global_config
redpitaya:
  hostname: ''
